"use client";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

export default function TranscriptionAnalysis() {
  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle>Transcription Analysis</CardTitle>
        <CardDescription>
          Analyzing the challenges of automatic transcription with regional
          dialects
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Tabs defaultValue="comparison">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="comparison">
              Transcription Comparison
            </TabsTrigger>
            <TabsTrigger value="wer">Word Error Rate</TabsTrigger>
            <TabsTrigger value="findings">Key Findings</TabsTrigger>
          </TabsList>

          <TabsContent value="comparison" className="space-y-4">
            <div className="prose max-w-none">
              <h3>Automatic vs. Manual Transcription</h3>
              <p>
                Below is a comparison between the automatic transcription
                generated by modern AI speech recognition software and the
                accurate manual transcription of a segment from the Abu Maluh
                cassettes. The differences highlight the challenges of
                preserving regional dialects through digital means.
              </p>
            </div>

            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Speaker</TableHead>
                  <TableHead>Automatic Transcription</TableHead>
                  <TableHead>Manual Transcription</TableHead>
                  <TableHead>Notes</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="font-medium">Abu Maluh</TableCell>
                  <TableCell>
                    يا ام مالح وين رحت انا ادور عليك من الصبح
                  </TableCell>
                  <TableCell>
                    يا أم مالوح وينش رحتي أنا أدوّر عليش من الصبح
                  </TableCell>
                  <TableCell>
                    Regional "ch" pronunciation missed; feminine endings changed
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Umm Maluh</TableCell>
                  <TableCell>رحت عند بنت عمي تقول انها مريضة</TableCell>
                  <TableCell>رحت عند بنت عمّي تقيل إنها مريضة</TableCell>
                  <TableCell>
                    Regional pronunciation of "taqil" mistranscribed
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Abu Maluh</TableCell>
                  <TableCell>الله يشفيها ما قلت لي ليه تاخرت</TableCell>
                  <TableCell>الله يشفيها ما قلتي لي ليش تأخرتي</TableCell>
                  <TableCell>
                    Regional question word "lesh" misrecognized
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Umm Maluh</TableCell>
                  <TableCell>انت ما سالت عنها قبل</TableCell>
                  <TableCell>إنت ما سألت عنّها قبل</TableCell>
                  <TableCell>Missed emphasis (shadda) on "ha"</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TabsContent>

          <TabsContent value="wer" className="space-y-4">
            <div className="prose max-w-none">
              <h3>Word Error Rate Analysis</h3>
              <p>
                The Word Error Rate (WER) measures the accuracy of automatic
                speech recognition by comparing it to a correct reference
                transcription. It's calculated as:
              </p>
              <div className="bg-gray-100 p-4 rounded-md text-center">
                <p className="font-mono text-lg">WER = (S + D + I) / N</p>
                <p className="text-sm">
                  Where S = substitutions, D = deletions, I = insertions, and N
                  = total words in the reference
                </p>
              </div>

              <p>For our sample of Abu Maluh dialogue:</p>

              <ul>
                <li>
                  <strong>Total words in reference:</strong> 42
                </li>
                <li>
                  <strong>Substitutions:</strong> 15
                </li>
                <li>
                  <strong>Deletions:</strong> 6
                </li>
                <li>
                  <strong>Insertions:</strong> 2
                </li>
                <li>
                  <strong>Word Error Rate:</strong> (15 + 6 + 2) / 42 = 54.8%
                </li>
              </ul>

              <p>
                This error rate is significantly higher than the typical 5-15%
                WER for Modern Standard Arabic speech recognition, illustrating
                the challenges of preserving regional dialects through automated
                means.
              </p>

              <h4>Error Distribution by Word Type:</h4>
              <ul>
                <li>Regional dialect-specific vocabulary: 38% of errors</li>
                <li>Feminine word endings: 24% of errors</li>
                <li>Pronunciation variations: 18% of errors</li>
                <li>Emphasis markers (shadda): 12% of errors</li>
                <li>Other errors: 8%</li>
              </ul>
            </div>
          </TabsContent>

          <TabsContent value="findings" className="space-y-4">
            <div className="prose max-w-none">
              <h3>Key Findings and Implications</h3>

              <p>
                Our analysis of automatic transcription of Abu Maluh cassettes
                reveals several important findings:
              </p>

              <h4>Dialect Preservation Challenges</h4>
              <p>
                The high word error rate (54.8%) demonstrates that current
                Arabic speech recognition systems are ill-equipped to handle
                regional dialects, particularly the Hail dialect featured in the
                Abu Maluh cassettes. This poses significant challenges for
                digital preservation of regional cultural heritage.
              </p>

              <h4>Homogenization of Language</h4>
              <p>
                Most automatic transcription errors involve replacing regional
                dialect features with Modern Standard Arabic, effectively
                erasing the linguistic distinctiveness that these cassettes
                preserved. This mirrors the same cultural standardization
                process that the cassettes were resisting through their use of
                regional dialect.
              </p>

              <h4>Cultural Context Loss</h4>
              <p>
                Many regional expressions with cultural significance are
                completely mistranscribed, losing their meaning. For example,
                regional idioms and cultural references specific to the Hail
                region are rendered meaningless by automatic transcription.
              </p>

              <h4>Implications for Digital Preservation</h4>
              <p>
                This analysis demonstrates that manual transcription by speakers
                familiar with the dialect remains essential for preserving
                regional cultural expressions, despite advances in speech
                recognition. The need for human expertise in cultural
                preservation efforts cannot be replaced by technology alone.
              </p>
            </div>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
}
