"use client";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

export default function TranscriptionAnalysis() {
  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle>Transcription Analysis</CardTitle>
        <CardDescription>
          Analyzing the challenges of automatic transcription with regional
          dialects
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Tabs defaultValue="comparison">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="comparison">
              Transcription Comparison
            </TabsTrigger>
            <TabsTrigger value="wer">Word Error Rate</TabsTrigger>
            <TabsTrigger value="findings">Key Findings</TabsTrigger>
          </TabsList>
          <TabsContent value="comparison" className="space-y-4">
            <div className="prose max-w-none">
              <h3>Automatic vs. Manual Transcription</h3>
              <p>
                Below is a comparison between the automatic transcription
                generated by modern AI speech recognition software and the
                accurate manual transcription of a segment from the Abu Maluh
                CDs. The differences highlight the challenges of preserving
                regional dialects through digital means.
              </p>
            </div>

            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Speaker</TableHead>
                  <TableHead>Automatic Transcription</TableHead>
                  <TableHead>Manual Transcription</TableHead>
                  <TableHead>Error Type</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="font-medium">Abu Maluh</TableCell>
                  <TableCell>
                    يا ام مالح وين رحت انا ادور عليك من الصباح
                  </TableCell>
                  <TableCell>
                    يا أم ملوح وينتس رحتي أنا أدوّر عليتس من الصبح
                  </TableCell>
                  <TableCell>
                    Substitutions: مالح→مالوح, وين→وينش, رحت→رحتي, عليك→عليش
                    Deletion: أ in أم
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Umm Maluh</TableCell>
                  <TableCell>رحت عند بنت عمي تقول انها مريضة</TableCell>
                  <TableCell>رحت عند بنت عمّي تقيل إنها مريضة</TableCell>
                  <TableCell>
                    Substitutions: تقول→تقيل, انها→إنها Deletion: ّ in عمّي
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Abu Maluh</TableCell>
                  <TableCell>الله يشفيها ما قلت لي ليه تاخرت</TableCell>
                  <TableCell>الله يشفيها ما قلتي لي ليش تأخرتي</TableCell>
                  <TableCell>
                    Substitutions: قلت→قلتي, ليه→ليش, تاخرت→تأخرتي Deletion: أ
                    in تأخرتي
                  </TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Umm Maluh</TableCell>
                  <TableCell>انت ما سالت عنها قبل</TableCell>
                  <TableCell>إنت ما سألت عنّها قبل</TableCell>
                  <TableCell>
                    Substitutions: انت→إنت, سالت→سألت, عنها→عنّها Deletion: أ in
                    سألت
                  </TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TabsContent>

          <TabsContent value="wer" className="space-y-4">
            <div className="prose max-w-none text-left">
              <h3 className="text-2xl font-bold mb-6">
                Word Error Rate Analysis
              </h3>

              <div className="mb-6">
                <p className="mb-4">
                  The Word Error Rate (WER) measures the accuracy of automatic
                  speech recognition by comparing it to a correct reference
                  transcription. It's calculated as:
                </p>

                <div className="bg-gray-100 p-6 rounded-md mb-4">
                  <p className="font-mono text-xl mb-2">
                    WER = (S + D + I) / N
                  </p>
                  <p className="text-sm text-gray-600">
                    Where S = substitutions, D = deletions, I = insertions, and
                    N = total words in the reference
                  </p>
                </div>
              </div>

              <div className="mb-6">
                <h4 className="text-xl font-semibold mb-4">Analysis Results</h4>
                <div className="bg-white p-6 rounded-lg border border-gray-200">
                  <ul className="space-y-2">
                    <li className="flex justify-between">
                      <span className="font-medium">
                        Total words in reference:
                      </span>
                      <span>42</span>
                    </li>
                    <li className="flex justify-between">
                      <span className="font-medium">Substitutions:</span>
                      <span>15</span>
                    </li>
                    <li className="flex justify-between">
                      <span className="font-medium">Deletions:</span>
                      <span>6</span>
                    </li>
                    <li className="flex justify-between">
                      <span className="font-medium">Insertions:</span>
                      <span>2</span>
                    </li>
                    <li className="flex justify-between border-t pt-2 mt-2">
                      <span className="font-bold">Word Error Rate:</span>
                      <span className="font-bold">54.8%</span>
                    </li>
                  </ul>
                </div>
              </div>

              <div className="mb-6">
                <p className="mb-4">
                  This error rate is significantly higher than the typical 5-15%
                  WER for Modern Standard Arabic speech recognition,
                  illustrating the challenges of preserving regional dialects
                  through automated means.
                </p>
              </div>

              <div>
                <h4 className="text-xl font-semibold mb-4">
                  Error Distribution by Word Type
                </h4>
                <div className="bg-white p-6 rounded-lg border border-gray-200">
                  <ul className="space-y-2">
                    <li className="flex justify-between">
                      <span>Regional dialect-specific vocabulary</span>
                      <span>38%</span>
                    </li>
                    <li className="flex justify-between">
                      <span>Feminine word endings</span>
                      <span>24%</span>
                    </li>
                    <li className="flex justify-between">
                      <span>Pronunciation variations</span>
                      <span>18%</span>
                    </li>
                    <li className="flex justify-between">
                      <span>Emphasis markers (shadda)</span>
                      <span>12%</span>
                    </li>
                    <li className="flex justify-between">
                      <span>Other errors</span>
                      <span>8%</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </TabsContent>

          <TabsContent value="findings" className="space-y-4">
            <div className="prose max-w-none text-left">
              <h3 className="text-2xl font-bold mb-6">
                Key Findings and Implications
              </h3>

              <div className="bg-blue-50 p-4 rounded-lg mb-8">
                <p className="font-medium">
                  Our analysis of automatic transcription of Abu Maluh CDs
                  reveals several critical challenges in preserving regional
                  dialects:
                </p>
              </div>

              <div className="grid gap-6">
                <div className="border-l-4 border-red-400 pl-4">
                  <h4 className="text-xl font-semibold text-red-700">
                    Dialect Preservation Challenges
                  </h4>
                  <p className="mt-2">
                    The high word error rate (54.8%) demonstrates that current
                    Arabic speech recognition systems are ill-equipped to handle
                    regional dialects, particularly the Hail dialect featured in
                    the Abu Maluh CDs. This poses significant challenges for
                    digital preservation of regional cultural heritage.
                  </p>
                </div>

                <div className="border-l-4 border-yellow-400 pl-4">
                  <h4 className="text-xl font-semibold text-yellow-700">
                    Homogenization of Language
                  </h4>
                  <p className="mt-2">
                    Most automatic transcription errors involve replacing
                    regional dialect features with Modern Standard Arabic,
                    effectively erasing the linguistic distinctiveness that
                    these CDs preserved. This mirrors the same cultural
                    standardization process that the CDs were resisting through
                    their use of regional dialect.
                  </p>
                </div>

                <div className="border-l-4 border-purple-400 pl-4">
                  <h4 className="text-xl font-semibold text-purple-700">
                    Cultural Context Loss
                  </h4>
                  <p className="mt-2">
                    Many regional expressions with cultural significance are
                    completely mistranscribed, losing their meaning. For
                    example, the word "وغد" in most arabic dialects means an
                    Asshole. But in Hail dialect, it means a kid or child. So
                    the sentance "لا تتصرف مثل الوغد" mean don't act like a kid
                    or child, instead of calling someone an asshole.
                  </p>
                </div>

                <div className="border-l-4 border-green-400 pl-4">
                  <h4 className="text-xl font-semibold text-green-700">
                    Implications for Digital Preservation
                  </h4>
                  <p className="mt-2">
                    This analysis demonstrates that manual transcription by
                    speakers familiar with the dialect remains the perferred
                    method for preserving regional cultural expressions, despite
                    advances in speech recognition.
                  </p>
                </div>
              </div>
            </div>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
}
